id: PF0F8F99A
initial_creation_type: ocr
source_metadata:
  volumes:
    7e526d17b72f460e8108a4f280ac709d:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ཤེས་རབ་སྒྲོན་མ།
      total_pages: 1605
      volume_number: 57
